//= import 'modernizr.js'

//= import 'jquery.js'
var $j = jQuery.noConflict();

//= import 'jquery-ui.js'
//= import 'jquery_sidr_min.js'
//= import 'jquery_scrollto_min.js'
//= import 'flexselect.js'
//= import 'liquidmetal.js'
//= import 'unslider.js'
//= import 'dom_url.js'

//= import '_basket.js'
//= import '_deal_selects.js'
//= import '_deal_wizard.js'
//= import '_dropdown_menu.js'
//= import '_favourites.js'
//= import '_flash.js'
//= import '_floater.js'
//= import '_money.js'
//= import '_nice_select.js'
//= import '_off_canvas.js'
//= import '_page.js'
//= import '_popup.js'
//= import '_product.js'
//= import '_sku_buttons.js'
//= import '_util.js'
//= import 'misc.js'
